trigger:
-main

pool:
vmImage: Default

variables:
  buildConfiguration: 'Release'

steps:
- script: sotnet build --configuration $(buildConfiguration)
  displayName 'dotnet build $(buildConfiguration)'